services:
  - type: web
    name: dementia-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8000

  - type: web
    name: dementia-streamlit
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run src/api/app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8501
      - key: API_URL
        fromService:
          name: dementia-api
          type: web
          property: host

